FROM node:18-alpine

WORKDIR /app

# Required for native modules like bcrypt
RUN apk add --no-cache python3 make g++

COPY backend/package*.json ./
RUN npm install --build-from-source

COPY backend .

EXPOSE 5000
CMD ["npm", "run", "dev"]
